services:
  - type: web
    name: cc-prediction
    env: production
    plan: free
    envVars:
      - key: MODEL_NAME
        fromSecret: modelName
      - key: MONITORING_CONFIG
        fromSecret: monitoringConfig
      - key: PORT
        value: "8501"
    healthCheckPath: /v1/models/cc-model
  - type: web
    name: cc-monitoring
    env: production
    plan: free
    envVars:
      - key: EXTERNAL_IP
        fromService: cc-prediction
  - type: web
    name: cc-visualization
    env: production
    plan: free
