services:
  - name: cc-prediction
    env: production
    plan: development
    envVars:
      - key: MODEL_NAME
        fromSecret: modelName
      - key: MONITORING_CONFIG
        fromSecret: monitoringConfig
      - key: PORT
        value: "8501"
    healthCheckPath: /v1/models/cc-model
    ports:
      - number: 8501
        protocol: TCP
  - name: cc-monitoring
    env: production
    plan: development
    envVars:
      - key: EXTERNAL_IP
        fromService: cc-prediction
    ports:
      - number: 9090
        protocol: TCP
  - name: cc-visualization
    env: production
    plan: development
    ports:
      - number: 3000
        protocol: TCP
