services:
  - type: web
    name: cc-prediction
    env: docker
    plan: free
    buildCommand: docker build -t mrbhaqee/cc-prediction .
    startCommand: docker run -p 8501:8501 mrbhaqee/cc-prediction
    healthCheckPath: /v1/models/cc-model
    internalPort: 8501

  - type: web
    name: cc-monitoring
    env: docker
    plan: free
    buildCommand: docker build -t mrbhaqee/cc-monitoring ./monitoring
    startCommand: docker run -p 9090:9090 mrbhaqee/cc-monitoring
    healthCheckPath: /metrics

  - type: web
    name: cc-visualization
    env: docker
    plan: free
    buildCommand: docker build -t mrbhaqee/cc-visualization ./visualization
    startCommand: docker run -p 3000:3000 mrbhaqee/cc-visualization
    healthCheckPath: /login
