services:
  - type: web
    name: cc-prediction
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t mrbhaqee/cc-prediction .
    healthCheckPath: /v1/models/cc-model

  - type: web
    name: cc-monitoring
    runtime: docker
    plan: free
    dockerfilePath: ./monitoring/Dockerfile
    buildCommand: docker build -t mrbhaqee/cc-monitoring ./monitoring
    healthCheckPath: /metrics

  - type: web
    name: cc-visualization
    runtime: docker
    dockerfilePath: ./visualization/Dockerfile
    plan: free
    buildCommand: docker build -t mrbhaqee/cc-visualization ./visualization
    healthCheckPath: /login
