services:
  - type: web
    name: cc-prediction
    env: production
    plan: development
    envVars:
      - key: MODEL_NAME
        fromSecret: modelName
      - key: MONITORING_CONFIG
        fromSecret: monitoringConfig
      - key: PORT
        value: "8501"
    healthCheckPath: /v1/models/cc-model
  # - type: web
  #   name: cc-monitoring
  #   env: production
  #   plan: development
  #   envVars:
  #     - key: EXTERNAL_IP
  #       value: <External IP> # Ganti dengan alamat IP yang sesuai
  # - type: web
  #   name: cc-visualization
  #   env: production
  #   plan: development
